# Site settings
title: Wode "Nimo" Ni
description: "Ph.D. student @ CMU"
url: "http://cs.cmu.edu"
baseurl: "/~woden"
google_analytics: "UA-112343565-3"
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Wode "Nimo" Ni'
  email: woden@cs.cmu.edu
  twitter_username: wodenimoni
  github_username: wodeni
  linkedin_username: wode-ni

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
destination: _site
paginate: 10
paginate_path: "/blog/:title"
permalink: /blog/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ["README.md", "Gemfile", "Gemfile.lock", "screenshot.png"]
plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-font-awesome-sass
