name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout Obsidian Pool Notes
        uses: actions/checkout@v4
        with:
          repository: wodeni/nimo-obsidian-notes-pool
          token: ${{ secrets.GH_PAT_OBSIDIAN_POOL }}
          path: ./pool-notes/

      - name: Log directory structure
        run: |
          ls -al
          ls -al pool-notes/

      - name: Install and Build
        run: |
          yarn
          yarn build 
        
      - name: Copy index.html to 404.html for routing
        run: |
          cp dist/index.html dist/404.html

      - name: Deploy website
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          working-directory: main
          branch: gh-pages
          folder: dist
          target-folder: .

      - name: Add .nojekyll
        run: |
          mkdir extra/
          touch extra/.nojekyll

      - name: Deploy .nojekyll
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
          clean: false
          working-directory: main
