name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout Obsidian Pool Notes
        uses: actions/checkout@v4
        with:
          repository: wodeni/nimo-obsidian-notes-pool
          token: ${{ secrets.GH_PAT_OBSIDIAN_POOL }}
          path: main/pool-notes/
      - name: Build deps
        run: yarn
        working-directory: main
      - name: Build the website
        run: yarn build
        working-directory: main
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: Deploy website
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          working-directory: main
          branch: gh-pages
          folder: dist
          target-folder: .
      - name: Add .nojekyll
        run: |
          mkdir extra/
          touch extra/.nojekyll
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: Deploy .nojekyll
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
          clean: false
          working-directory: main
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: Deploy to cmu server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CMU_SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.CMU_HOST }}
          REMOTE_USER: ${{ secrets.CMU_USER }}
          TARGET: ${{ secrets.CMU_TARGET }}
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT
