name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          path: main

      - name: Checkout Obsidian Pool Notes
        uses: actions/checkout@v4
        with:
          repository: wodeni/nimo-obsidian-notes-pool
          token: ${{ secrets.GH_PAT_OBSIDIAN_POOL }}
          path: main/pool-notes/

      - name: Install and Build
        run: |
          yarn
          yarn build -- --base /pr-preview/pr-${{ github.event.pull_request.number }}/
        working-directory: main

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/
          working-directory: main
        
